In [1]:
import numpy as np
from PIL import Image
import cv2

In [2]:
import os
TRAIN_DIR = "MiddEval3/trainingQ/"
IMAGE_LEFT, IMAGE_RIGHT = "im0.png", "im1.png"
TRAIN_LISTS = [filename for filename in os.listdir(TRAIN_DIR)]
print(TRAIN_LISTS)

['ArtL', 'Motorcycle', 'MotorcycleE', 'Vintage', 'Playroom', 'Jadeplant', 'Shelves', 'Piano', 'PianoL', 'Adirondack', 'Teddy', 'Recycle', 'PlaytableP', 'Pipes', 'Playtable']


In [3]:
def distortion():
    SIFT = cv2.xfeatures2d.SIFT_create()

distortion()

In [56]:
def stereo_match(imgL, imgR, kernel=6, search_range=30, name="default.png"):
    w, h = imgL.size
    left, right = np.asarray(imgL), np.asarray(imgR)
    depth = np.zeros((h, w), np.uint8) # PIL and numpy have different indexing systems.
    
    #depth.shape = h, w
    half_kernel = kernel//2
    depth_offset = 255//search_range
    for y in range(half_kernel, h-half_kernel):
        print(".", end="", flush=True)
        for x in range(half_kernel, w-half_kernel):
            optimal_offset = 0
            ssd_min = 256*256
            for search_idx in range(search_range):
                ssd = 0
                for u in range(-half_kernel, half_kernel):
                    for v in range(-half_kernel, half_kernel):
                        ssd += (int(left[y+u, x+v]) - int(right[y+u, x+v-search_idx]))**2
                if ssd < ssd_min:
                    ssd_min = ssd
                    optimal_offset = search_idx
            depth[y, x] = optimal_offset * depth_offset
    print(depth)
    Image.fromarray(depth).save(name)

In [57]:
for train in TRAIN_LISTS[1:5]:
    train_dir = TRAIN_DIR + train + "/"
    print(train_dir)
    left_img = train_dir + IMAGE_LEFT
    right_img = train_dir + IMAGE_RIGHT
    iml = Image.open(left_img).convert("L")
    imr = Image.open(right_img).convert("L")
    # stereo_match(imgL=iml, imgR=imr, name=train_dir+"output.png")

MiddEval3/trainingQ/Motorcycle/
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
MiddEval3/trainingQ/MotorcycleE/
....................................................................................................................................................................................................................................................................................................................................